import { ChainConfig } from '@zenith/types';

export const ZENITH_SUPPORTED_CHAINS: Record<string, ChainConfig> = {
  // =========================================================================
  // TIER 1 — CORE / FULL PRODUCTION (8 Networks)
  // =========================================================================
  ethereum: {
    id: 'ethereum',
    chainId: 1,
    canonicalName: 'Ethereum',
    shortName: 'Ethereum',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_1',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'ERC-1155', 'ERC-4626', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [
      { url: 'https://eth.llamarpc.com', priority: 1, status: 'HEALTHY' },
      { url: 'https://rpc.ankr.com/eth', priority: 2, status: 'HEALTHY' },
      { url: 'https://cloudflare-eth.com', priority: 3, status: 'HEALTHY' }
    ],
    explorer: {
      name: 'Etherscan',
      baseUrl: 'https://etherscan.io',
      txPath: '/tx/',
      addressPath: '/address/',
      tokenPath: '/token/'
    },
    finality: {
      reorgSafetyBlocks: 64,
      instantFinality: false,
      typicalBlockTimeSec: 12,
      safeFinalityTimeSec: 768
    },
    capabilities: {
      wallet: true,
      tokenDiscovery: true,
      tokenRisk: true,
      priceData: true,
      liquidityDiscovery: true,
      swap: true,
      smartRouting: true,
      simulation: true,
      portfolio: true,
      history: true,
      mevProtection: true,
      crossChain: true,
      zenithLiquidity: true,
      api: true,
      sdk: true,
      supportsEIP1559: true,
      supportsPermit2: true,
      supportsFlashbots: true,
      supportsSimulation: true,
      supportsBatchTransactions: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'DEEP',
    productionStatus: 'ACTIVE',
    color: '#627EEA',
    iconURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png'
  },

  base: {
    id: 'base',
    chainId: 8453,
    canonicalName: 'Base',
    shortName: 'Base',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_1',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'ERC-1155', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [
      { url: 'https://mainnet.base.org', priority: 1, status: 'HEALTHY' },
      { url: 'https://base.llamarpc.com', priority: 2, status: 'HEALTHY' }
    ],
    explorer: {
      name: 'BaseScan',
      baseUrl: 'https://basescan.org',
      txPath: '/tx/',
      addressPath: '/address/',
      tokenPath: '/token/'
    },
    finality: {
      reorgSafetyBlocks: 20,
      instantFinality: false,
      typicalBlockTimeSec: 2,
      safeFinalityTimeSec: 60
    },
    capabilities: {
      wallet: true,
      tokenDiscovery: true,
      tokenRisk: true,
      priceData: true,
      liquidityDiscovery: true,
      swap: true,
      smartRouting: true,
      simulation: true,
      portfolio: true,
      history: true,
      mevProtection: true,
      crossChain: true,
      zenithLiquidity: true,
      api: true,
      sdk: true,
      supportsEIP1559: true,
      supportsPermit2: true,
      supportsFlashbots: false,
      supportsSimulation: true,
      supportsBatchTransactions: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'DEEP',
    productionStatus: 'ACTIVE',
    color: '#0052FF',
    iconURI: 'https://assets.coingecko.com/coins/images/31388/small/base.png'
  },

  arbitrum: {
    id: 'arbitrum',
    chainId: 42161,
    canonicalName: 'Arbitrum',
    shortName: 'Arbitrum',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_1',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'ERC-1155', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [
      { url: 'https://arb1.arbitrum.io/rpc', priority: 1, status: 'HEALTHY' },
      { url: 'https://arbitrum.llamarpc.com', priority: 2, status: 'HEALTHY' }
    ],
    explorer: {
      name: 'Arbiscan',
      baseUrl: 'https://arbiscan.io',
      txPath: '/tx/',
      addressPath: '/address/',
      tokenPath: '/token/'
    },
    finality: {
      reorgSafetyBlocks: 20,
      instantFinality: false,
      typicalBlockTimeSec: 0.25,
      safeFinalityTimeSec: 30
    },
    capabilities: {
      wallet: true,
      tokenDiscovery: true,
      tokenRisk: true,
      priceData: true,
      liquidityDiscovery: true,
      swap: true,
      smartRouting: true,
      simulation: true,
      portfolio: true,
      history: true,
      mevProtection: true,
      crossChain: true,
      zenithLiquidity: true,
      api: true,
      sdk: true,
      supportsEIP1559: true,
      supportsPermit2: true,
      supportsFlashbots: false,
      supportsSimulation: true,
      supportsBatchTransactions: true,
      hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'DEEP',
    productionStatus: 'ACTIVE',
    color: '#28A0F0',
    iconURI: 'https://assets.coingecko.com/coins/images/16547/small/arbitrum.png'
  },

  optimism: {
    id: 'optimism',
    chainId: 10,
    canonicalName: 'Optimism',
    shortName: 'Optimism',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_1',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'ERC-1155', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [
      { url: 'https://mainnet.optimism.io', priority: 1, status: 'HEALTHY' },
      { url: 'https://optimism.llamarpc.com', priority: 2, status: 'HEALTHY' }
    ],
    explorer: {
      name: 'OP Etherscan',
      baseUrl: 'https://optimistic.etherscan.io',
      txPath: '/tx/',
      addressPath: '/address/',
      tokenPath: '/token/'
    },
    finality: {
      reorgSafetyBlocks: 20,
      instantFinality: false,
      typicalBlockTimeSec: 2,
      safeFinalityTimeSec: 60
    },
    capabilities: {
      wallet: true,
      tokenDiscovery: true,
      tokenRisk: true,
      priceData: true,
      liquidityDiscovery: true,
      swap: true,
      smartRouting: true,
      simulation: true,
      portfolio: true,
      history: true,
      mevProtection: true,
      crossChain: true,
      zenithLiquidity: true,
      api: true,
      sdk: true,
      supportsEIP1559: true,
      supportsPermit2: true,
      supportsFlashbots: false,
      supportsSimulation: true,
      supportsBatchTransactions: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'DEEP',
    productionStatus: 'ACTIVE',
    color: '#FF0420',
    iconURI: 'https://assets.coingecko.com/coins/images/25244/small/Optimism.png'
  },

  polygon: {
    id: 'polygon',
    chainId: 137,
    canonicalName: 'Polygon',
    shortName: 'Polygon',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_1',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'ERC-1155', 'Permit2'],
    nativeCurrency: { name: 'Polygon Ecosystem Token', symbol: 'POL', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/4713/small/polygon.png' },
    rpcEndpoints: [
      { url: 'https://polygon-rpc.com', priority: 1, status: 'HEALTHY' },
      { url: 'https://rpc.ankr.com/polygon', priority: 2, status: 'HEALTHY' }
    ],
    explorer: {
      name: 'PolygonScan',
      baseUrl: 'https://polygonscan.com',
      txPath: '/tx/',
      addressPath: '/address/',
      tokenPath: '/token/'
    },
    finality: {
      reorgSafetyBlocks: 128,
      instantFinality: false,
      typicalBlockTimeSec: 2,
      safeFinalityTimeSec: 256
    },
    capabilities: {
      wallet: true,
      tokenDiscovery: true,
      tokenRisk: true,
      priceData: true,
      liquidityDiscovery: true,
      swap: true,
      smartRouting: true,
      simulation: true,
      portfolio: true,
      history: true,
      mevProtection: false,
      crossChain: true,
      zenithLiquidity: true,
      api: true,
      sdk: true,
      supportsEIP1559: true,
      supportsPermit2: true,
      supportsFlashbots: false,
      supportsSimulation: true,
      supportsBatchTransactions: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'DEEP',
    productionStatus: 'ACTIVE',
    color: '#8247E5',
    iconURI: 'https://assets.coingecko.com/coins/images/4713/small/polygon.png'
  },

  bnb: {
    id: 'bnb',
    chainId: 56,
    canonicalName: 'BNB Chain',
    shortName: 'BNB Chain',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_1',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['BEP-20', 'BEP-721', 'BEP-1155', 'Permit2'],
    nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png' },
    rpcEndpoints: [
      { url: 'https://bsc-dataseed.binance.org', priority: 1, status: 'HEALTHY' },
      { url: 'https://rpc.ankr.com/bsc', priority: 2, status: 'HEALTHY' }
    ],
    explorer: {
      name: 'BscScan',
      baseUrl: 'https://bscscan.com',
      txPath: '/tx/',
      addressPath: '/address/',
      tokenPath: '/token/'
    },
    finality: {
      reorgSafetyBlocks: 15,
      instantFinality: true,
      typicalBlockTimeSec: 3,
      safeFinalityTimeSec: 45
    },
    capabilities: {
      wallet: true,
      tokenDiscovery: true,
      tokenRisk: true,
      priceData: true,
      liquidityDiscovery: true,
      swap: true,
      smartRouting: true,
      simulation: true,
      portfolio: true,
      history: true,
      mevProtection: false,
      crossChain: true,
      zenithLiquidity: true,
      api: true,
      sdk: true,
      supportsEIP1559: true,
      supportsPermit2: true,
      supportsFlashbots: false,
      supportsSimulation: true,
      supportsBatchTransactions: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'DEEP',
    productionStatus: 'ACTIVE',
    color: '#F3BA2F',
    iconURI: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png'
  },

  avalanche: {
    id: 'avalanche',
    chainId: 43114,
    canonicalName: 'Avalanche',
    shortName: 'Avalanche',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_1',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ARC-20', 'ARC-721', 'ARC-1155', 'Permit2'],
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png' },
    rpcEndpoints: [
      { url: 'https://api.avax.network/ext/bc/C/rpc', priority: 1, status: 'HEALTHY' },
      { url: 'https://rpc.ankr.com/avalanche', priority: 2, status: 'HEALTHY' }
    ],
    explorer: {
      name: 'Snowtrace',
      baseUrl: 'https://snowtrace.io',
      txPath: '/tx/',
      addressPath: '/address/',
      tokenPath: '/token/'
    },
    finality: {
      reorgSafetyBlocks: 1,
      instantFinality: true,
      typicalBlockTimeSec: 1,
      safeFinalityTimeSec: 2
    },
    capabilities: {
      wallet: true,
      tokenDiscovery: true,
      tokenRisk: true,
      priceData: true,
      liquidityDiscovery: true,
      swap: true,
      smartRouting: true,
      simulation: true,
      portfolio: true,
      history: true,
      mevProtection: false,
      crossChain: true,
      zenithLiquidity: true,
      api: true,
      sdk: true,
      supportsEIP1559: true,
      supportsPermit2: true,
      supportsFlashbots: false,
      supportsSimulation: true,
      supportsBatchTransactions: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'DEEP',
    productionStatus: 'ACTIVE',
    color: '#E84142',
    iconURI: 'https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png'
  },

  solana: {
    id: 'solana',
    chainId: 101,
    canonicalName: 'Solana',
    shortName: 'Solana',
    executionEnvironment: 'SOLANA',
    category: 'LAYER_1',
    tier: 'TIER_1',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['SOL', 'SPL Token', 'Token-2022'],
    nativeCurrency: { name: 'Solana', symbol: 'SOL', decimals: 9, logoURI: 'https://assets.coingecko.com/coins/images/4128/small/solana.png' },
    rpcEndpoints: [
      { url: 'https://api.mainnet-beta.solana.com', priority: 1, status: 'HEALTHY' },
      { url: 'https://solana-mainnet.g.alchemy.com/v2/demo', priority: 2, status: 'HEALTHY' }
    ],
    explorer: {
      name: 'Solscan',
      baseUrl: 'https://solscan.io',
      txPath: '/tx/',
      addressPath: '/account/',
      tokenPath: '/token/'
    },
    finality: {
      reorgSafetyBlocks: 32,
      instantFinality: false,
      typicalBlockTimeSec: 0.4,
      safeFinalityTimeSec: 12.8
    },
    capabilities: {
      wallet: true,
      tokenDiscovery: true,
      tokenRisk: true,
      priceData: true,
      liquidityDiscovery: true,
      swap: true,
      smartRouting: true,
      simulation: true,
      portfolio: true,
      history: true,
      mevProtection: false,
      crossChain: true,
      zenithLiquidity: true,
      api: true,
      sdk: true,
      supportsEIP1559: false,
      supportsPermit2: false,
      supportsFlashbots: false,
      supportsSimulation: true,
      supportsBatchTransactions: true,
      hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'DEEP',
    productionStatus: 'ACTIVE',
    color: '#14F195',
    iconURI: 'https://assets.coingecko.com/coins/images/4128/small/solana.png'
  },

  // =========================================================================
  // TIER 2 — FULL TRADING / EXPANDING PRODUCTION (22 Networks)
  // =========================================================================
  unichain: {
    id: 'unichain',
    chainId: 130,
    canonicalName: 'Unichain',
    shortName: 'Unichain',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://mainnet.unichain.org', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Uniscan', baseUrl: 'https://uniscan.xyz', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 1, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: true, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#FF007A',
    iconURI: 'https://assets.coingecko.com/coins/images/12504/small/uniswap-uni.png'
  },

  linea: {
    id: 'linea',
    chainId: 59144,
    canonicalName: 'Linea',
    shortName: 'Linea',
    executionEnvironment: 'EVM',
    category: 'ZK_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.linea.build', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'LineaScan', baseUrl: 'https://lineascan.build', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#121212',
    iconURI: 'https://assets.coingecko.com/coins/images/31294/small/linea.png'
  },

  zksync: {
    id: 'zksync',
    chainId: 324,
    canonicalName: 'zkSync',
    shortName: 'zkSync',
    executionEnvironment: 'EVM',
    category: 'ZK_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Account Abstraction', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://mainnet.era.zksync.io', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'zkSync Explorer', baseUrl: 'https://explorer.zksync.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 1, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#8C8DFC',
    iconURI: 'https://assets.coingecko.com/coins/images/27897/small/zksync.jpeg'
  },

  scroll: {
    id: 'scroll',
    chainId: 534352,
    canonicalName: 'Scroll',
    shortName: 'Scroll',
    executionEnvironment: 'EVM',
    category: 'ZK_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.scroll.io', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'ScrollScan', baseUrl: 'https://scrollscan.com', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 3, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#FFE7B9',
    iconURI: 'https://assets.coingecko.com/coins/images/32280/small/scroll.png'
  },

  blast: {
    id: 'blast',
    chainId: 81457,
    canonicalName: 'Blast',
    shortName: 'Blast',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Native Yield', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.blast.io', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'BlastScan', baseUrl: 'https://blastscan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#FCFC03',
    iconURI: 'https://assets.coingecko.com/coins/images/35515/small/blast.png'
  },

  zora: {
    id: 'zora',
    chainId: 7777777,
    canonicalName: 'Zora',
    shortName: 'Zora',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.zora.energy', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Zora Explorer', baseUrl: 'https://explorer.zora.energy', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#000000',
    iconURI: 'https://assets.coingecko.com/coins/images/30894/small/zora.png'
  },

  worldchain: {
    id: 'worldchain',
    chainId: 480,
    canonicalName: 'World Chain',
    shortName: 'World Chain',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'WorldID Priority', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://worldchain-mainnet.g.alchemy.com/public', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'WorldScan', baseUrl: 'https://worldscan.org', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#1E1E1E',
    iconURI: 'https://assets.coingecko.com/coins/images/31062/small/worldcoin.png'
  },

  mantle: {
    id: 'mantle',
    chainId: 5000,
    canonicalName: 'Mantle',
    shortName: 'Mantle',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'Permit2'],
    nativeCurrency: { name: 'Mantle', symbol: 'MNT', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/30980/small/mantle.png' },
    rpcEndpoints: [{ url: 'https://rpc.mantle.xyz', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Mantle Explorer', baseUrl: 'https://explorer.mantle.xyz', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 1, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#000000',
    iconURI: 'https://assets.coingecko.com/coins/images/30980/small/mantle.png'
  },

  celo: {
    id: 'celo',
    chainId: 42220,
    canonicalName: 'Celo',
    shortName: 'Celo',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Fee Currencies', 'Permit2'],
    nativeCurrency: { name: 'Celo', symbol: 'CELO', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/11090/small/celo.png' },
    rpcEndpoints: [{ url: 'https://forno.celo.org', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'CeloScan', baseUrl: 'https://celoscan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 5, safeFinalityTimeSec: 5 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: false, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#35D07F',
    iconURI: 'https://assets.coingecko.com/coins/images/11090/small/celo.png'
  },

  gnosis: {
    id: 'gnosis',
    chainId: 100,
    canonicalName: 'Gnosis',
    shortName: 'Gnosis',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'ERC-721', 'Permit2'],
    nativeCurrency: { name: 'xDAI', symbol: 'xDAI', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/11062/small/xdai.png' },
    rpcEndpoints: [{ url: 'https://rpc.gnosischain.com', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Gnosisscan', baseUrl: 'https://gnosisscan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 5, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#133629',
    iconURI: 'https://assets.coingecko.com/coins/images/662/small/gnosis_logo.png'
  },

  sonic: {
    id: 'sonic',
    chainId: 146,
    canonicalName: 'Sonic',
    shortName: 'Sonic',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Permit2'],
    nativeCurrency: { name: 'Sonic', symbol: 'S', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/38108/small/sonic.png' },
    rpcEndpoints: [{ url: 'https://rpc.soniclabs.com', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'SonicScan', baseUrl: 'https://sonicscan.org', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 0.5, safeFinalityTimeSec: 1 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#0055FF',
    iconURI: 'https://assets.coingecko.com/coins/images/38108/small/sonic.png'
  },

  soneium: {
    id: 'soneium',
    chainId: 1868,
    canonicalName: 'Soneium',
    shortName: 'Soneium',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.soneium.org', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Soneium Explorer', baseUrl: 'https://explorer.soneium.org', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#002B49',
    iconURI: 'https://assets.coingecko.com/coins/images/39906/small/soneium.png'
  },

  berachain: {
    id: 'berachain',
    chainId: 80094,
    canonicalName: 'Berachain',
    shortName: 'Berachain',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Proof of Liquidity', 'Permit2'],
    nativeCurrency: { name: 'Bera', symbol: 'BERA', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/29729/small/berachain.png' },
    rpcEndpoints: [{ url: 'https://rpc.berachain.com', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Berascan', baseUrl: 'https://berascan.com', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#8B4513',
    iconURI: 'https://assets.coingecko.com/coins/images/29729/small/berachain.png'
  },

  cronos: {
    id: 'cronos',
    chainId: 25,
    canonicalName: 'Cronos',
    shortName: 'Cronos',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['CRC-20', 'ERC-20', 'Permit2'],
    nativeCurrency: { name: 'Cronos', symbol: 'CRO', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/7310/small/cro_token_logo.png' },
    rpcEndpoints: [{ url: 'https://evm.cronos.org', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Cronoscan', baseUrl: 'https://cronoscan.com', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 5, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#002D74',
    iconURI: 'https://assets.coingecko.com/coins/images/7310/small/cro_token_logo.png'
  },

  xlayer: {
    id: 'xlayer',
    chainId: 196,
    canonicalName: 'X Layer',
    shortName: 'X Layer',
    executionEnvironment: 'EVM',
    category: 'ZK_ROLLUP',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'OKB Native Gas', 'Permit2'],
    nativeCurrency: { name: 'OKB', symbol: 'OKB', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/4463/small/okb_token.png' },
    rpcEndpoints: [{ url: 'https://rpc.xlayer.tech', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'OKLink X Layer', baseUrl: 'https://www.oklink.com/xlayer', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 1, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#000000',
    iconURI: 'https://assets.coingecko.com/coins/images/4463/small/okb_token.png'
  },

  sei: {
    id: 'sei',
    chainId: 1329,
    canonicalName: 'Sei',
    shortName: 'Sei',
    executionEnvironment: 'EVM',
    category: 'HIGH_THROUGHPUT_L1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Parallel EVM', 'Permit2'],
    nativeCurrency: { name: 'Sei', symbol: 'SEI', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/28205/small/Sei_Logo_-_Transparent.png' },
    rpcEndpoints: [{ url: 'https://evm-rpc.sei-apis.com', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'SeiTrace', baseUrl: 'https://seitrace.com', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 0.4, safeFinalityTimeSec: 0.8 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#9B1C2E',
    iconURI: 'https://assets.coingecko.com/coins/images/28205/small/Sei_Logo_-_Transparent.png'
  },

  sui: {
    id: 'sui',
    chainId: 0,
    canonicalName: 'Sui',
    shortName: 'Sui',
    executionEnvironment: 'MOVE',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['Move Coin', 'Move Object'],
    nativeCurrency: { name: 'Sui', symbol: 'SUI', decimals: 9, logoURI: 'https://assets.coingecko.com/coins/images/26375/small/sui-ocean-square.png' },
    rpcEndpoints: [{ url: 'https://fullnode.mainnet.sui.io', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'SuiScan', baseUrl: 'https://suiscan.xyz', txPath: '/tx/', addressPath: '/account/', tokenPath: '/coin/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 0.4, safeFinalityTimeSec: 0.8 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#4DA2FF',
    iconURI: 'https://assets.coingecko.com/coins/images/26375/small/sui-ocean-square.png'
  },

  aptos: {
    id: 'aptos',
    chainId: 1,
    canonicalName: 'Aptos',
    shortName: 'Aptos',
    executionEnvironment: 'MOVE',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['Aptos Coin', 'Fungible Asset'],
    nativeCurrency: { name: 'Aptos', symbol: 'APT', decimals: 8, logoURI: 'https://assets.coingecko.com/coins/images/26455/small/aptos_round.png' },
    rpcEndpoints: [{ url: 'https://fullnode.mainnet.aptoslabs.com/v1', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Aptos Explorer', baseUrl: 'https://explorer.aptoslabs.com', txPath: '/txn/', addressPath: '/account/', tokenPath: '/coin/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 0.5, safeFinalityTimeSec: 1 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#222222',
    iconURI: 'https://assets.coingecko.com/coins/images/26455/small/aptos_round.png'
  },

  near: {
    id: 'near',
    chainId: 397,
    canonicalName: 'NEAR',
    shortName: 'NEAR',
    executionEnvironment: 'NEAR',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['NEP-141', 'NEP-171'],
    nativeCurrency: { name: 'NEAR Protocol', symbol: 'NEAR', decimals: 24, logoURI: 'https://assets.coingecko.com/coins/images/10365/small/near.png' },
    rpcEndpoints: [{ url: 'https://rpc.mainnet.near.org', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'NearBlocks', baseUrl: 'https://nearblocks.io', txPath: '/txns/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 2, instantFinality: true, typicalBlockTimeSec: 1.2, safeFinalityTimeSec: 2.4 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#000000',
    iconURI: 'https://assets.coingecko.com/coins/images/10365/small/near.png'
  },

  cosmoshub: {
    id: 'cosmoshub',
    chainId: 0,
    canonicalName: 'Cosmos Hub',
    shortName: 'Cosmos',
    executionEnvironment: 'COSMOS',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['Native', 'IBC', 'CW20'],
    nativeCurrency: { name: 'Cosmos', symbol: 'ATOM', decimals: 6, logoURI: 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png' },
    rpcEndpoints: [{ url: 'https://cosmos-rpc.publicnode.com', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Mintscan', baseUrl: 'https://www.mintscan.io/cosmos', txPath: '/tx/', addressPath: '/account/', tokenPath: '/assets/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 6, safeFinalityTimeSec: 6 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#2E3148',
    iconURI: 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png'
  },

  osmosis: {
    id: 'osmosis',
    chainId: 0,
    canonicalName: 'Osmosis',
    shortName: 'Osmosis',
    executionEnvironment: 'COSMOS',
    category: 'LAYER_1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['IBC', 'Superfluid Staking', 'CW20'],
    nativeCurrency: { name: 'Osmosis', symbol: 'OSMO', decimals: 6, logoURI: 'https://assets.coingecko.com/coins/images/16724/small/osmo.png' },
    rpcEndpoints: [{ url: 'https://osmosis-rpc.publicnode.com', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Mintscan', baseUrl: 'https://www.mintscan.io/osmosis', txPath: '/tx/', addressPath: '/account/', tokenPath: '/assets/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 6, safeFinalityTimeSec: 6 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#8A2BE2',
    iconURI: 'https://assets.coingecko.com/coins/images/16724/small/osmo.png'
  },

  injective: {
    id: 'injective',
    chainId: 0,
    canonicalName: 'Injective',
    shortName: 'Injective',
    executionEnvironment: 'COSMOS',
    category: 'HIGH_THROUGHPUT_L1',
    tier: 'TIER_2',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['Native', 'IBC', 'Injective Orderbook'],
    nativeCurrency: { name: 'Injective', symbol: 'INJ', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/12882/small/injective_logo.png' },
    rpcEndpoints: [{ url: 'https://sentry.lcd.injective.network', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Injective Explorer', baseUrl: 'https://explorer.injective.network', txPath: '/transaction/', addressPath: '/account/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 0.8, safeFinalityTimeSec: 1.6 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: true, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#00F2FE',
    iconURI: 'https://assets.coingecko.com/coins/images/12882/small/injective_logo.png'
  },

  // =========================================================================
  // TIER 3 — EXPERIMENTAL / LIMITED PRODUCTION (17 Networks)
  // =========================================================================
  arbitrumnova: {
    id: 'arbitrumnova',
    chainId: 42170,
    canonicalName: 'Arbitrum Nova',
    shortName: 'Nova',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'AnyTrust'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://nova.arbitrum.io/rpc', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'NovaScan', baseUrl: 'https://nova.arbiscan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 0.25, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      supportsEIP1559: true, hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#E06214',
    iconURI: 'https://assets.coingecko.com/coins/images/16547/small/arbitrum.png'
  },

  polygonzkevm: {
    id: 'polygonzkevm',
    chainId: 1101,
    canonicalName: 'Polygon zkEVM',
    shortName: 'Polygon zkEVM',
    executionEnvironment: 'EVM',
    category: 'ZK_ROLLUP',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://zkevm-rpc.com', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Polygon zkEVM Scan', baseUrl: 'https://zkevm.polygonscan.com', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      supportsEIP1559: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#7B3FE4',
    iconURI: 'https://assets.coingecko.com/coins/images/4713/small/polygon.png'
  },

  mode: {
    id: 'mode',
    chainId: 34443,
    canonicalName: 'Mode',
    shortName: 'Mode',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://mainnet.mode.network', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'ModeScan', baseUrl: 'https://modescan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      supportsEIP1559: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#DFFE00',
    iconURI: 'https://assets.coingecko.com/coins/images/34346/small/mode.png'
  },

  taiko: {
    id: 'taiko',
    chainId: 167000,
    canonicalName: 'Taiko',
    shortName: 'Taiko',
    executionEnvironment: 'EVM',
    category: 'ZK_ROLLUP',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Based Contestable'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.mainnet.taiko.xyz', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'TaikoScan', baseUrl: 'https://taikoscan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 3, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      supportsEIP1559: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#E81899',
    iconURI: 'https://assets.coingecko.com/coins/images/35887/small/taiko.png'
  },

  metis: {
    id: 'metis',
    chainId: 1088,
    canonicalName: 'Metis',
    shortName: 'Metis',
    executionEnvironment: 'EVM',
    category: 'OPTIMISTIC_ROLLUP',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20'],
    nativeCurrency: { name: 'Metis', symbol: 'METIS', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/15595/small/metis.png' },
    rpcEndpoints: [{ url: 'https://andromeda.metis.io/?owner=1088', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Metis Explorer', baseUrl: 'https://andromeda-explorer.metis.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 2, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      supportsEIP1559: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#00DACC',
    iconURI: 'https://assets.coingecko.com/coins/images/15595/small/metis.png'
  },

  moonbeam: {
    id: 'moonbeam',
    chainId: 1284,
    canonicalName: 'Moonbeam',
    shortName: 'Moonbeam',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'XC-20'],
    nativeCurrency: { name: 'Glimmer', symbol: 'GLMR', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/22459/small/glmr.png' },
    rpcEndpoints: [{ url: 'https://rpc.api.moonbeam.network', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Moonscan', baseUrl: 'https://moonscan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 6, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      supportsEIP1559: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#53CBC9',
    iconURI: 'https://assets.coingecko.com/coins/images/22459/small/glmr.png'
  },

  moonriver: {
    id: 'moonriver',
    chainId: 1285,
    canonicalName: 'Moonriver',
    shortName: 'Moonriver',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'XC-20'],
    nativeCurrency: { name: 'Moonriver', symbol: 'MOVR', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/17984/small/moonriver.png' },
    rpcEndpoints: [{ url: 'https://rpc.api.moonriver.moonbeam.network', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Moonriver Scan', baseUrl: 'https://moonriver.moonscan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 6, safeFinalityTimeSec: 30 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      supportsEIP1559: true, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#F4B400',
    iconURI: 'https://assets.coingecko.com/coins/images/17984/small/moonriver.png'
  },

  rootstock: {
    id: 'rootstock',
    chainId: 30,
    canonicalName: 'Rootstock',
    shortName: 'Rootstock',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Merged Mining BTC'],
    nativeCurrency: { name: 'Smart Bitcoin', symbol: 'RBTC', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/5041/small/rbtc.png' },
    rpcEndpoints: [{ url: 'https://public-node.rsk.co', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Rootstock Explorer', baseUrl: 'https://explorer.rootstock.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 30, safeFinalityTimeSec: 180 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      supportsEIP1559: false, hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#00B48A',
    iconURI: 'https://assets.coingecko.com/coins/images/5041/small/rbtc.png'
  },

  tron: {
    id: 'tron',
    chainId: 728126428,
    canonicalName: 'Tron',
    shortName: 'Tron',
    executionEnvironment: 'TVM',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['TRC-10', 'TRC-20'],
    nativeCurrency: { name: 'Tron', symbol: 'TRX', decimals: 6, logoURI: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png' },
    rpcEndpoints: [{ url: 'https://api.trongrid.io', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'TRONSCAN', baseUrl: 'https://tronscan.org', txPath: '/#/transaction/', addressPath: '/#/address/', tokenPath: '/#/token20/' },
    finality: { reorgSafetyBlocks: 19, instantFinality: false, typicalBlockTimeSec: 3, safeFinalityTimeSec: 60 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#FF0013',
    iconURI: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png'
  },

  ton: {
    id: 'ton',
    chainId: 0,
    canonicalName: 'TON',
    shortName: 'TON',
    executionEnvironment: 'TON',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['TON', 'Jetton'],
    nativeCurrency: { name: 'Toncoin', symbol: 'TON', decimals: 9, logoURI: 'https://assets.coingecko.com/coins/images/17980/small/ton_symbol.png' },
    rpcEndpoints: [{ url: 'https://toncenter.com/api/v2/jsonRPC', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Tonscan', baseUrl: 'https://tonscan.org', txPath: '/tx/', addressPath: '/address/', tokenPath: '/jetton/' },
    finality: { reorgSafetyBlocks: 5, instantFinality: false, typicalBlockTimeSec: 5, safeFinalityTimeSec: 25 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: false, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#0088CC',
    iconURI: 'https://assets.coingecko.com/coins/images/17980/small/ton_symbol.png'
  },

  hedera: {
    id: 'hedera',
    chainId: 295,
    canonicalName: 'Hedera',
    shortName: 'Hedera',
    executionEnvironment: 'EVM',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['HTS', 'ERC-20'],
    nativeCurrency: { name: 'Hedera', symbol: 'HBAR', decimals: 8, logoURI: 'https://assets.coingecko.com/coins/images/3688/small/hbar.png' },
    rpcEndpoints: [{ url: 'https://mainnet.hashio.io/api', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'HashScan', baseUrl: 'https://hashscan.io', txPath: '/mainnet/transaction/', addressPath: '/mainnet/account/', tokenPath: '/mainnet/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 3, safeFinalityTimeSec: 5 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: false, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#222222',
    iconURI: 'https://assets.coingecko.com/coins/images/3688/small/hbar.png'
  },

  algorand: {
    id: 'algorand',
    chainId: 0,
    canonicalName: 'Algorand',
    shortName: 'Algorand',
    executionEnvironment: 'UTXO',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ASA (Algorand Standard Asset)'],
    nativeCurrency: { name: 'Algorand', symbol: 'ALGO', decimals: 6, logoURI: 'https://assets.coingecko.com/coins/images/4380/small/download.png' },
    rpcEndpoints: [{ url: 'https://mainnet-api.algonode.cloud', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'AlgoScan', baseUrl: 'https://algoscan.app', txPath: '/tx/', addressPath: '/address/', tokenPath: '/asset/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 3.3, safeFinalityTimeSec: 3.3 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: false, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EMERGING',
    productionStatus: 'ACTIVE',
    color: '#000000',
    iconURI: 'https://assets.coingecko.com/coins/images/4380/small/download.png'
  },

  stellar: {
    id: 'stellar',
    chainId: 0,
    canonicalName: 'Stellar',
    shortName: 'Stellar',
    executionEnvironment: 'STELLAR',
    category: 'PAYMENTS_NETWORK',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['XLM', 'SEP-41', 'Soroban Smart Contracts'],
    nativeCurrency: { name: 'Stellar Lumens', symbol: 'XLM', decimals: 7, logoURI: 'https://assets.coingecko.com/coins/images/100/small/Stellar_symbol_black_RGB.png' },
    rpcEndpoints: [{ url: 'https://horizon.stellar.org', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'StellarExpert', baseUrl: 'https://stellar.expert/explorer/public', txPath: '/tx/', addressPath: '/account/', tokenPath: '/asset/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 5, safeFinalityTimeSec: 5 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: false, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#000000',
    iconURI: 'https://assets.coingecko.com/coins/images/100/small/Stellar_symbol_black_RGB.png'
  },

  xrpl: {
    id: 'xrpl',
    chainId: 0,
    canonicalName: 'XRP Ledger',
    shortName: 'XRPL',
    executionEnvironment: 'XRPL',
    category: 'PAYMENTS_NETWORK',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['XRP', 'Trustline Assets', 'AMM'],
    nativeCurrency: { name: 'XRP', symbol: 'XRP', decimals: 6, logoURI: 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png' },
    rpcEndpoints: [{ url: 'https://xrplcluster.com', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'XRPScan', baseUrl: 'https://xrpscan.com', txPath: '/tx/', addressPath: '/account/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 3.5, safeFinalityTimeSec: 3.5 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: false, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#23292F',
    iconURI: 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png'
  },

  cardano: {
    id: 'cardano',
    chainId: 0,
    canonicalName: 'Cardano',
    shortName: 'Cardano',
    executionEnvironment: 'UTXO',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ADA', 'Native Assets', 'Plutus'],
    nativeCurrency: { name: 'Cardano', symbol: 'ADA', decimals: 6, logoURI: 'https://assets.coingecko.com/coins/images/975/small/cardano.png' },
    rpcEndpoints: [{ url: 'https://cardano-mainnet.blockfrost.io/api/v0', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Cardanoscan', baseUrl: 'https://cardanoscan.io', txPath: '/transaction/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 20, safeFinalityTimeSec: 120 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: false, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#0033AD',
    iconURI: 'https://assets.coingecko.com/coins/images/975/small/cardano.png'
  },

  polkadot: {
    id: 'polkadot',
    chainId: 0,
    canonicalName: 'Polkadot',
    shortName: 'Polkadot',
    executionEnvironment: 'SUBSTRATE',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['DOT', 'Asset Hub Assets', 'XCM'],
    nativeCurrency: { name: 'Polkadot', symbol: 'DOT', decimals: 10, logoURI: 'https://assets.coingecko.com/coins/images/12171/small/polkadot.png' },
    rpcEndpoints: [{ url: 'https://rpc.polkadot.io', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Subscan', baseUrl: 'https://polkadot.subscan.io', txPath: '/extrinsic/', addressPath: '/account/', tokenPath: '/asset/' },
    finality: { reorgSafetyBlocks: 2, instantFinality: true, typicalBlockTimeSec: 6, safeFinalityTimeSec: 12 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#E6007A',
    iconURI: 'https://assets.coingecko.com/coins/images/12171/small/polkadot.png'
  },

  icp: {
    id: 'icp',
    chainId: 0,
    canonicalName: 'Internet Computer',
    shortName: 'ICP',
    executionEnvironment: 'ICP',
    category: 'LAYER_1',
    tier: 'TIER_3',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ICP', 'ICRC-1', 'ICRC-2'],
    nativeCurrency: { name: 'Internet Computer', symbol: 'ICP', decimals: 8, logoURI: 'https://assets.coingecko.com/coins/images/14495/small/Internet_Computer_logo.png' },
    rpcEndpoints: [{ url: 'https://ic0.app', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'ICScan', baseUrl: 'https://dashboard.internetcomputer.org', txPath: '/transaction/', addressPath: '/account/', tokenPath: '/canister/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 1, safeFinalityTimeSec: 2 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: false, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'GROWING',
    productionStatus: 'ACTIVE',
    color: '#29ABE2',
    iconURI: 'https://assets.coingecko.com/coins/images/14495/small/Internet_Computer_logo.png'
  },

  // =========================================================================
  // TIER 4 — RESEARCH / ADAPTER READY (5 Target Networks)
  // =========================================================================
  bitcoin: {
    id: 'bitcoin',
    chainId: 0,
    canonicalName: 'Bitcoin',
    shortName: 'Bitcoin',
    executionEnvironment: 'BITCOIN',
    category: 'LAYER_1',
    tier: 'TIER_4',
    operationalStatus: 'PARTIALLY_AVAILABLE',
    supportedStandards: ['BTC', 'Ordinals', 'Runes', 'BRC-20'],
    nativeCurrency: { name: 'Bitcoin', symbol: 'BTC', decimals: 8, logoURI: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png' },
    rpcEndpoints: [
      { url: 'https://mempool.space/api', priority: 1, status: 'HEALTHY' },
      { url: 'https://blockstream.info/api', priority: 2, status: 'HEALTHY' }
    ],
    explorer: { name: 'Mempool', baseUrl: 'https://mempool.space', txPath: '/tx/', addressPath: '/address/', tokenPath: '/address/' },
    finality: { reorgSafetyBlocks: 6, instantFinality: false, typicalBlockTimeSec: 600, safeFinalityTimeSec: 3600 },
    capabilities: {
      wallet: false, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: false,
      swap: false, smartRouting: false, simulation: false, portfolio: true, history: true,
      mevProtection: false, crossChain: false, zenithLiquidity: false, api: true, sdk: true,
      hasSubSecondBlocks: false
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EXPERIMENTAL',
    productionStatus: 'PLANNED',
    color: '#F7931A',
    iconURI: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png'
  },

  monad: {
    id: 'monad',
    chainId: 10143,
    canonicalName: 'Monad',
    shortName: 'Monad',
    executionEnvironment: 'EVM',
    category: 'HIGH_THROUGHPUT_L1',
    tier: 'TIER_4',
    operationalStatus: 'MAINTENANCE',
    supportedStandards: ['ERC-20', 'Parallel EVM', 'Permit2'],
    nativeCurrency: { name: 'Monad', symbol: 'MON', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/34407/small/monad.png' },
    rpcEndpoints: [{ url: 'https://rpc.monad.xyz', priority: 1, status: 'DEGRADED' }],
    explorer: { name: 'MonadScan', baseUrl: 'https://monadscan.xyz', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 0.2, safeFinalityTimeSec: 0.8 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: false, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EXPERIMENTAL',
    productionStatus: 'BETA',
    color: '#836EF9',
    iconURI: 'https://assets.coingecko.com/coins/images/34407/small/monad.png'
  },

  robinhood: {
    id: 'robinhood',
    chainId: 42161,
    canonicalName: 'Robinhood Chain',
    shortName: 'Robinhood',
    executionEnvironment: 'EVM',
    category: 'ORBIT_RWA',
    tier: 'TIER_4',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'RWA Gated Token', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.robinhood.io', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Robinhood Explorer', baseUrl: 'https://explorer.robinhood.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 10, instantFinality: false, typicalBlockTimeSec: 0.25, safeFinalityTimeSec: 10 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: true, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: true, blockedRegions: ['OFAC_SANCTIONED'], tokenizedSecuritiesPresent: true, requiresAccreditationNotice: true },
    liquidityMaturity: 'EXPERIMENTAL',
    productionStatus: 'BETA',
    color: '#00C805',
    iconURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png'
  },

  tempo: {
    id: 'tempo',
    chainId: 204,
    canonicalName: 'Tempo',
    shortName: 'Tempo',
    executionEnvironment: 'EVM',
    category: 'PAYMENTS_NETWORK',
    tier: 'TIER_4',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Real-Time Payment Channel'],
    nativeCurrency: { name: 'Tempo', symbol: 'TEMPO', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.tempo.network', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'Tempo Explorer', baseUrl: 'https://explorer.tempo.network', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 0.1, safeFinalityTimeSec: 0.5 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: true, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EXPERIMENTAL',
    productionStatus: 'BETA',
    color: '#6366F1',
    iconURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png'
  },

  megaeth: {
    id: 'megaeth',
    chainId: 4242,
    canonicalName: 'MegaETH',
    shortName: 'MegaETH',
    executionEnvironment: 'EVM',
    category: 'HIGH_THROUGHPUT_L1',
    tier: 'TIER_4',
    operationalStatus: 'HEALTHY',
    supportedStandards: ['ERC-20', 'Real-Time Sub-millisecond', 'Permit2'],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18, logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    rpcEndpoints: [{ url: 'https://rpc.megaeth.systems', priority: 1, status: 'HEALTHY' }],
    explorer: { name: 'MegaScan', baseUrl: 'https://megascan.io', txPath: '/tx/', addressPath: '/address/', tokenPath: '/token/' },
    finality: { reorgSafetyBlocks: 1, instantFinality: true, typicalBlockTimeSec: 0.01, safeFinalityTimeSec: 0.1 },
    capabilities: {
      wallet: true, tokenDiscovery: true, tokenRisk: true, priceData: true, liquidityDiscovery: true,
      swap: true, smartRouting: true, simulation: true, portfolio: true, history: true,
      mevProtection: true, crossChain: true, zenithLiquidity: true, api: true, sdk: true,
      supportsEIP1559: true, supportsPermit2: true, hasSubSecondBlocks: true
    },
    regulatoryScope: { jurisdictionGated: false },
    liquidityMaturity: 'EXPERIMENTAL',
    productionStatus: 'BETA',
    color: '#A855F7',
    iconURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png'
  }
};
